import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { parseModel } from "../src/engine/parser";
import { flatten } from "../src/engine/flattener";
import { resolveEncodings } from "../src/engine/encodingResolver";
import { emit } from "../src/engine/codeEmitter";
import type { EncodedMachine } from "../src/engine/types";

// Slice one function definition out of the emitted .cc (up to its closing
// brace at column 0).
const fn = (cc: string, sig: string) => {
  const at = cc.indexOf(sig);
  return at < 0 ? "" : cc.slice(at, cc.indexOf("\n}", at) + 2);
};

// A model with no CommPattern send_down/send_up pair.
const bareMachine = (): EncodedMachine => ({
  name: "m0",
  chain: ["m0"],
  variables: [],
  variableTypes: new Map(),
  events: [
    { label: "INITIALISATION", parameters: [], guards: [], actions: [] },
    { label: "tick", parameters: [], guards: [], actions: [] },
  ],
  encodings: new Map(),
});

const load = (n: string) =>
  ({ name: `${n}.bum`, xml: readFileSync(`tests/fixtures/shdecom/${n}.bum`, "utf8") });
const gen = (target: string, files: string[], name: string) =>
  emit(resolveEncodings(flatten(parseModel(files.map(load)), target)), name);

describe("codeEmitter", () => {
  const tree = gen("pM1", ["pM1"], "Pm1App");
  const file = (ext: string) => tree.find((f) => f.path === `Pm1App.${ext}`)!.content;

  it("emits exactly three files named after the output name", () => {
    expect(tree.map((f) => f.path).sort()).toEqual(["Pm1App.cc", "Pm1App.h", "Pm1App.ned"]);
  });
  it("stamps every file with a provenance banner (source model, no roadmap text)", () => {
    for (const ext of ["h", "cc", "ned"]) {
      expect(file(ext)).toContain("Generated by wsn-codegen from the Event-B machine pM1");
      expect(file(ext)).not.toMatch(/next step/i);
    }
  });
  it("banner names the whole merged chain, not one fixed machine", () => {
    const merged = gen("pM3", ["pM1", "uM2", "pM3"], "WsnApp");
    for (const f of merged) {
      expect(f.content).toContain(
        "Generated by wsn-codegen from the Event-B refinement chain pM1 → uM2 → pM3 (merged into one module)",
      );
    }
  });
  it("declares ENC-typed state fields", () => {
    const h = file("h");
    expect(h).toContain("std::set<std::pair<Node, PktId>> sentUp");
    expect(h).toContain("std::map<PktId, std::set<Node>> ctlNeighbours");
    expect(h).toContain("std::set<PktId> createdPkts");
    expect(h).toContain("std::map<PktId, Node> pktFwdr");
  });
  it("wraps the class in the INET SensorApp shell: ApplicationBase + socket callback", () => {
    const h = file("h");
    expect(h).toContain("class Pm1App : public ApplicationBase, public INetworkSocket::ICallback");
    expect(h).toContain('#include "inet/applications/base/ApplicationBase.h"');
    // INetworkSocket.h uses Protocol without including it; Protocol.h must
    // come first (same include order as SensorApp.h) or the header won't parse.
    expect(h).toMatch(/#include "inet\/common\/Protocol\.h"[\s\S]*#include "inet\/networklayer\/contract\/INetworkSocket\.h"/);
    expect(h).toContain("void handleMessageWhenUp(cMessage *msg) override;");
    expect(h).not.toContain("RoutingProtocolBase");
  });
  it("merges SensorApp's transmit structure into the pattern's send_down (thesis S4)", () => {
    const cc = file("cc");
    const body = fn(cc, "bool Pm1App::send_down");
    expect(body).toContain("if (!(sentDown.count({x, pkt}) > 0)) return false;"); // model guard first
    expect(body).toContain("packet->addTag<L3AddressReq>()->setDestAddress(sinkAddress);");
    expect(body).toContain("emit(packetSentSignal, packet);");
    expect(body).toContain("socket->send(packet);");
    // merged, not duplicated: no separate shell send function (comments may
    // still cite SensorApp::sendSensorPacket as provenance), no invented names
    expect(cc).not.toMatch(/void Pm1App::sendSensorPacket/);
    expect(cc).not.toMatch(/sendSensorPacket\(\);/);
    expect(cc).not.toMatch(/void Pm1App::sendDown\(/);
    expect(cc).not.toMatch(/void Pm1App::sendUp\(/);
    expect(file("h")).not.toMatch(/virtual void sendSensorPacket/);
  });
  it("merges SensorApp's receive structure into the pattern's send_up (thesis S5)", () => {
    const cc = file("cc");
    const body = fn(cc, "bool Pm1App::send_up");
    expect(body).toContain("if (!(sentUp.count({x, pkt}) == 0)) return false;"); // model guards kept
    expect(body).toContain("receivedCount++;");
    expect(body).toContain("sentUp.insert({x, pkt});"); // model actions kept
  });
  it("socketDataArrived keeps the packet-object mechanics and points at send_up", () => {
    const cc = file("cc");
    const body = fn(cc, "void Pm1App::socketDataArrived");
    expect(body).toContain("emit(packetReceivedSignal, packet);");
    expect(body).toContain("delete packet;");
    expect(body).toContain("send_up");
  });
  it("timer branch of handleMessageWhenUp points at send_down and reschedules", () => {
    const cc = file("cc");
    const body = fn(cc, "void Pm1App::handleMessageWhenUp");
    expect(body).toContain("send_down");
    expect(body).toContain("scheduleNextSensing(simTime());");
    expect(body).toContain("socket->processMessage(msg);");
  });
  it("falls back to SensorApp's own sendSensorPacket when a model has no CommPattern pair", () => {
    const cc = emit(bareMachine(), "BareApp").find((f) => f.path === "BareApp.cc")!.content;
    expect(cc).toContain("void BareApp::sendSensorPacket()");
    expect(cc).toContain("socket->send(packet);");
    const recv = fn(cc, "void BareApp::socketDataArrived");
    expect(recv).toContain("receivedCount++;");
  });
  it("implements the lifecycle handlers with SensorApp bodies, not empty stubs", () => {
    const cc = file("cc");
    expect(cc).toMatch(/void Pm1App::handleStartOperation\([^)]*\)\s*\{[^}]*openSocket\(\);/);
    expect(cc).toMatch(/void Pm1App::handleStopOperation\([^)]*\)\s*\{[^}]*cancelNextSensing\(\);/);
    expect(cc).toMatch(/void Pm1App::handleCrashOperation\([^)]*\)\s*\{[^}]*destroy\(\);/);
  });
  it("reads SensorApp parameters in initialize(INITSTAGE_LOCAL)", () => {
    const cc = file("cc");
    expect(cc).toContain("void Pm1App::initialize(int stage)");
    expect(cc).toContain("ApplicationBase::initialize(stage);");
    expect(cc).toContain('timer = new cMessage("sensingTimer");');
  });
  it("marks the identity-binding extension points in the dispatcher and receive callback", () => {
    const cc = file("cc");
    expect(cc).toContain("EXTENSION POINT (send-down flow)");
    expect(cc).toContain("EXTENSION POINT (send-up flow)");
  });
  it("emits a guarded method per event with early-return guards", () => {
    const cc = file("cc");
    expect(cc).toMatch(/bool Pm1App::start_tx\([^)]*\)\s*\{/);
    expect(cc).toContain("if (!(sentDown.count({x, pkt}) == 0)) return false;");
    expect(cc).toContain("return true;");
  });
  it("renders an action-less non-pattern event as a bool predicate", () => {
    const cc = emit(bareMachine(), "BareApp").find((f) => f.path === "BareApp.cc")!.content;
    expect(cc).toMatch(/bool BareApp::tick\(\)\s*\{\s*return true;\s*\}/);
  });
  it("emits a NED-resolvable module: standalone simple like IApp, class bound via @class", () => {
    const ned = file("ned");
    expect(ned).not.toContain("RoutingProtocolBase");
    expect(ned).toContain("simple Pm1App like IApp");
    expect(ned).toContain("@class(Pm1App)");
    expect(ned).toContain("input socketIn @labels(ITransportPacket/up)");
    expect(ned).toContain("output socketOut @labels(ITransportPacket/down)");
  });
  it("declares the SensorApp parameters and signals in the NED module", () => {
    const ned = file("ned");
    expect(ned).toContain('string sinkAddress = default("")');
    expect(ned).toContain("volatile double sensingInterval @unit(s)");
    expect(ned).toContain("int payloadLength @unit(B)");
    expect(ned).toContain('string networkProtocol = default("")');
    expect(ned).toContain("@signal[packetSent](type=inet::Packet)");
    expect(ned).toContain("@signal[packetReceived](type=inet::Packet)");
  });
});
