import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { parseModel } from "../src/engine/parser";
import { flatten } from "../src/engine/flattener";
import { resolveEncodings } from "../src/engine/encodingResolver";
import { emit } from "../src/engine/codeEmitter";

const load = (n: string) =>
  ({ name: `${n}.bum`, xml: readFileSync(`tests/fixtures/shdecom/${n}.bum`, "utf8") });
const gen = (target: string, files: string[], name: string) =>
  emit(resolveEncodings(flatten(parseModel(files.map(load)), target)), name);

describe("codeEmitter", () => {
  const tree = gen("pM1", ["pM1"], "Pm1App");
  const file = (ext: string) => tree.find((f) => f.path === `Pm1App.${ext}`)!.content;

  it("emits exactly three files named after the output name", () => {
    expect(tree.map((f) => f.path).sort()).toEqual(["Pm1App.cc", "Pm1App.h", "Pm1App.ned"]);
  });
  it("stamps every file with a provenance banner (source model, no roadmap text)", () => {
    for (const ext of ["h", "cc", "ned"]) {
      expect(file(ext)).toContain("Generated by wsn-codegen from the Event-B machine pM1");
      expect(file(ext)).not.toMatch(/next step/i);
    }
  });
  it("banner names the whole merged chain, not one fixed machine", () => {
    const merged = gen("pM3", ["pM1", "uM2", "pM3"], "WsnApp");
    for (const f of merged) {
      expect(f.content).toContain(
        "Generated by wsn-codegen from the Event-B refinement chain pM1 → uM2 → pM3 (merged into one module)",
      );
    }
  });
  it("declares ENC-typed state fields", () => {
    const h = file("h");
    expect(h).toContain("std::set<std::pair<Node, PktId>> sentUp");
    expect(h).toContain("std::map<PktId, std::set<Node>> ctlNeighbours");
    expect(h).toContain("std::set<PktId> createdPkts");
    expect(h).toContain("std::map<PktId, Node> pktFwdr");
  });
  it("wraps the class in the INET SensorApp shell: ApplicationBase + socket callback", () => {
    const h = file("h");
    expect(h).toContain("class Pm1App : public ApplicationBase, public INetworkSocket::ICallback");
    expect(h).toContain('#include "inet/applications/base/ApplicationBase.h"');
    // INetworkSocket.h uses Protocol without including it; Protocol.h must
    // come first (same include order as SensorApp.h) or the header won't parse.
    expect(h).toMatch(/#include "inet\/common\/Protocol\.h"[\s\S]*#include "inet\/networklayer\/contract\/INetworkSocket\.h"/);
    expect(h).toContain("void handleMessageWhenUp(cMessage *msg) override;");
    expect(h).not.toContain("RoutingProtocolBase");
  });
  it("emits SensorApp's own send function, no invented shell names", () => {
    const cc = file("cc");
    expect(cc).toContain("void Pm1App::sendSensorPacket()");
    expect(cc).toContain("packet->addTag<L3AddressReq>()->setDestAddress(sinkAddress);");
    expect(cc).toContain("emit(packetSentSignal, packet);");
    expect(cc).toContain("socket->send(packet);");
    // The model's send_down/send_up bool event methods are the ONLY send pair
    // beyond SensorApp's: the shell must not add a colliding sendDown/sendUp.
    expect(cc).not.toMatch(/void Pm1App::sendDown\(/);
    expect(cc).not.toMatch(/void Pm1App::sendUp\(/);
  });
  it("receives in socketDataArrived directly, as SensorApp does", () => {
    const cc = file("cc");
    const body = cc.slice(cc.indexOf("void Pm1App::socketDataArrived"));
    expect(body).toContain("receivedCount++;");
    expect(body).toContain("emit(packetReceivedSignal, packet);");
    expect(body).toContain("delete packet;");
  });
  it("dispatches in handleMessageWhenUp: timer → sendSensorPacket, socket msg → receive path", () => {
    const cc = file("cc");
    const body = cc.slice(cc.indexOf("void Pm1App::handleMessageWhenUp"));
    expect(body).toContain("sendSensorPacket();");
    expect(body).toContain("scheduleNextSensing(simTime());");
    expect(body).toContain("socket->processMessage(msg);");
  });
  it("implements the lifecycle handlers with SensorApp bodies, not empty stubs", () => {
    const cc = file("cc");
    expect(cc).toMatch(/void Pm1App::handleStartOperation\([^)]*\)\s*\{[^}]*openSocket\(\);/);
    expect(cc).toMatch(/void Pm1App::handleStopOperation\([^)]*\)\s*\{[^}]*cancelNextSensing\(\);/);
    expect(cc).toMatch(/void Pm1App::handleCrashOperation\([^)]*\)\s*\{[^}]*destroy\(\);/);
  });
  it("reads SensorApp parameters in initialize(INITSTAGE_LOCAL)", () => {
    const cc = file("cc");
    expect(cc).toContain("void Pm1App::initialize(int stage)");
    expect(cc).toContain("ApplicationBase::initialize(stage);");
    expect(cc).toContain('timer = new cMessage("sensingTimer");');
  });
  it("marks the Event-B wiring extension points inside sendDown and sendUp", () => {
    const cc = file("cc");
    expect(cc).toContain("EXTENSION POINT (send-down flow)");
    expect(cc).toContain("EXTENSION POINT (send-up flow)");
  });
  it("emits a guarded method per event with early-return guards", () => {
    const cc = file("cc");
    expect(cc).toMatch(/bool Pm1App::start_tx\([^)]*\)\s*\{/);
    expect(cc).toContain("if (!(sentDown.count({x, pkt}) == 0)) return false;");
    expect(cc).toContain("return true;");
  });
  it("renders an action-less event as a bool predicate (send_down)", () => {
    const cc = file("cc");
    expect(cc).toMatch(/bool Pm1App::send_down\([^)]*\)\s*\{\s*return [^;]+;\s*\}/);
  });
  it("emits a NED-resolvable module: standalone simple like IApp, class bound via @class", () => {
    const ned = file("ned");
    expect(ned).not.toContain("RoutingProtocolBase");
    expect(ned).toContain("simple Pm1App like IApp");
    expect(ned).toContain("@class(Pm1App)");
    expect(ned).toContain("input socketIn @labels(ITransportPacket/up)");
    expect(ned).toContain("output socketOut @labels(ITransportPacket/down)");
  });
  it("declares the SensorApp parameters and signals in the NED module", () => {
    const ned = file("ned");
    expect(ned).toContain('string sinkAddress = default("")');
    expect(ned).toContain("volatile double sensingInterval @unit(s)");
    expect(ned).toContain("int payloadLength @unit(B)");
    expect(ned).toContain('string networkProtocol = default("")');
    expect(ned).toContain("@signal[packetSent](type=inet::Packet)");
    expect(ned).toContain("@signal[packetReceived](type=inet::Packet)");
  });
});
